<style type="text/css">
    .zend-form ul {
        margin: 0px;
        padding: 0px;
        font-family: georgia;
        font-size: 1em;
    }

    .zend-form ul li {
        padding: 10px;
        margin: 10px;
        list-style: none;
        background-color: bisque;
        clear: both;
    }

    .label-div {
        width: 220px;
        float: left;
    }

    .zend-form ul li input, .zend-form ul li select {
        font-family: georgia;
        font-size: 1em;
        width: 220px;
        float: left;
    }

    .errors {
        width: 440px;
        color: red;
    }
    
    .clear {
        clear: both;
    }

    .element-group {
        width: 100%;
    }
</style>
<div class="zend-form">
    <?php echo $this->form ;?>
</div>